service: serverless-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-notes

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
   notesTableName: ${self:custom.notesTableName}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - "Fn::GetAtt": [ NotesTable, Arn ]

functions:
  createNote:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes
    # - method: POST request
    handler: src/functions/notes/createNotes.main
    events:
      - http:
          path: notes
          cors: true
          method: post
          authorizer: aws_iam

  getNote:
    # Defines an HTTP API endpoint that calls the main function in getNote.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: src/functions/notes/getNote.main
    events:
      - http:
          path: notes/{id}
          cors: true
          method: get
          authorizer: aws_iam

  getAllNotes:
    # Defines an HTTP API endpoint that calls the main function in getAllNotes.js
    # - path: url path is /notes
    # - method: GET request
    handler: src/functions/notes/getAllNotes.main
    events:
      - http:
          path: notes
          cors: true
          method: get
          authorizer: aws_iam

  updateNote:
    # Defines an HTTP API endpoint that calls the main function in updateNote.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: src/functions/notes/updateNote.main
    events:
      - http:
          path: notes/{id}
          cors: true
          method: put
          authorizer: aws_iam
  
  deleteNote:
    # Defines an HTTP API endpoint that calls the main function in deleteNote.js
    # - path: url path is /notes/{id}
    # - method: DELETE request
    handler: src/functions/notes/deleteNote.main
    events:
      - http:
          path: notes/{id}
          cors: true
          method: delete
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

